### ISSUE TITLE
Issue generating subtitles

### ISSUE THREAD

**Issue by pordeciralgo** [HenestrosaDev/audiotext#19] opened 2024-06-04 13:58 UTC
Steps to reproduce
------------------

1. Tried to generate subtitles for this classic movie: https://1drv.ms/v/s!AvxL3H5dkUh1h4k-5Z8uG14x1YrLfQ?e=nAnSTF
2. Settings:
-Language: English (also tested with Spanish, same result)
-Transcribe from File
-Transcribe using WhisperX
-Translate to English: NOT CHECKED
-Generate subtitles: CHECKED
-Highlight words: NOT CHECKED
-Max. line count: 2
-Max. line width: 42
-Model size: large-v2
-Compute type: float32
-Batch size: 8
-Use CPU: NOT CHECKED
Running 2.2.1 on Windows 10 x64
3. Generate transcription works OK.

Expected behaviour
------------------

Save transcription generates .txt, .srt and .vtt files.

It does behave as expected with other audio files.

Actual behaviour
----------------

Save transcription gets stuck on an empty 0-byte .txt. Neither .srt nor .vtt are generated.

System information
------------------

- Windows 10 x64
- Spanish system language (es-ES)
- Audiotext 2.2.1

**Comment by pordeciralgo** [comment] 2024-06-04 14:00
Please let me know when you're downloaded the file, so I can unshare it. Thank you in advance.

**Comment by HenestrosaDev** [comment] 2024-06-04 14:22
I've already downloaded the file. I'll take a look to see what's going on.

**Comment by HenestrosaDev** [comment] 2024-06-04 17:13
It seems that the problem is caused by the ♪ symbols, which throw a `UnicodeEncodeError` in the `save_transcription` method of the `main_controller` when writing the transcription text to a .txt file. 

This is the stacktrace for reference:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\u266a' in position 0: character maps to <undefined>
```

I've already solved this by encoding the file with `utf-8`. I'll close the issue as soon as I release version 2.2.2, which should be sometime today or tomorrow.

**Comment by HenestrosaDev** [comment] 2024-06-05 21:57
I've just released the new version, so I'm closing this issue. Please create a new one if you encounter any problems.

**Closed by HenestrosaDev** 2024-06-05 21:57 UTC
